# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, db_index=True)),
                ('state', django_fsm.FSMField(default='new', max_length=50)),
                ('rejection_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetches', to='catalog.Content')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('url', models.URLField(db_index=True, max_length=1024, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fetch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetches', to='catalog.Location'),
        ),
    ]
